version: "3"

services:
  quiklink_app:
    build:
      context: .
    container_name: quiklink_app
    volumes:
      - ./:/usr/src/app
    command:
      - bash
      - -c
      - chmod +x prod.sh && ./prod.sh
    ports:
      - "8080:8080"
    tty: true

volumes:
  data:
    driver: local
