version: "3"

services:
  quiklink_app:
    build:
      context: .
    container_name: quiklink_app
    volumes:
      - ./:/usr/src/app
    command:
      - bash
      - -c
      - go build -o Quiklink_BE cmd/*.go && ./Quiklink_BE -dbname=Quiklink_BE -dbuser=postgres
    ports:
      - "8080:8080"
    tty: true
    depends_on:
      - postgres

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: Quiklink_BE
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./data:/data/db
    ports:
      - "5432:5432"

volumes:
  data:
    driver: local
