version: "3"

services:
  quiklink_app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: quiklink-docker
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    env_file:
      - .env
    tty: true

  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: quiklink-docker-test
    volumes:
      - .:/app
    env_file:
      - .env
    command: ["go", "test", "-v", "./..."]
