version: "3"

services:
  quiklink_app:
    build:
      context: .
      dockerfile: Dockerfile
    image: quiklink-docker
    container_name: quiklink_app
    platform: linux/amd64
    volumes:
      - ./:/usr/src/app
    ports:
      - "8080:8080"
    tty: true

volumes:
  data:
    driver: local
