name: Deploy Quiklink-App
on:
  push:
    branches:
      - main

env:
  SHA: $(git rev-parse HEAD)

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: 'actions/checkout@v4'

      - name: Docker Login
        run: |-
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Set Identity Provider
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/lunar-analyzer-419703/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
          service_account: 'quiklink-deployer@lunar-analyzer-419703.iam.gserviceaccount.com'

      - name: Set Project
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          project_id: 'lunar-analyzer-419703'

      - name: Auth
        run: |-
          gcloud --quiet auth configure-docker

      - name: Get Credentials
        uses: 'google-github-actions/get-gke-credentials@v2'
        with:
          cluster_name: 'qlink-prod-cluster'
          location: 'us-west1-a'

      - name: Build
        run: |-
          docker build -t rahuldhiman93/quiklink-prod:latest -t rahuldhiman93/quiklink-prod:${{ env.SHA }} -f ./

      - name: Push
        run: |-
          docker push rahuldhiman93/quiklink-prod:latest
          docker push rahuldhiman93/quiklink-prod:${{ env.SHA }}

      - name: Apply
        run: |-
          kubectl apply -f kubernetes
          kubectl set image deployments/client-deployment client=rahuldhiman93/quiklink-prod:${{ env.SHA }}