# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - quiklink

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.AzureAppService_ContainerUsername_148fa2536f854decb710b5805c28d9b5 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_b73ee184edea465eaeaba1c1304bd74c }}

    - name: Build
      run: |-
        docker build -t rahuldhiman93/quiklink-prod:latest -t rahuldhiman93/quiklink-prod:${{  github.sha }} .

    - name: Push
      run: |-
        docker push rahuldhiman93/quiklink-prod:latest
        docker push rahuldhiman93/quiklink-prod:${{  github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'quiklink'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_0b4137a7e67648e9a81d2f653633a6f4 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_148fa2536f854decb710b5805c28d9b5 }}/rahuldhiman93/quiklink-prod:latest'