name: Go Testing

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    env:
      IN_PRODUCTION: 'true'
      USE_CACHE: 'true'
      DBHOST: ${{ secrets.DBHOST }}
      DBPORT: '5432'
      DBNAME: 'Quiklink_BE'
      DBUSER: 'postgres.qpzeyjkejgkwzeihilwx'
      DBPASS: ${{ secrets.DBPASS }}
      DBSSL: 'prefer'

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Install dependencies
        run: go mod download

      - name: Test
        run: go test -v ./...